### ISSUE TITLE
Portfolio and facility uri make more unique.

### ISSUE THREAD

**Issue by demattosanthony** [syyclops/brontes#42]
## Description

We need to make the portfolio and faiclity uris more unique unique so even if the names are the same the uris are still different

For the portfolio we can use:

- [x] Unix timestamp of creation: 1715043700
- [x] The portfolio name. flinthillschools

For the facility we can use:

- [x] The location, country, city, state. US-DC-VA
- [x] Unix timestamp of creation: 1715043700
- [x] Facility name

## Tasks

- [x] Create a model of an address. It should be a data model with country, city, state, zip code, etc
- [x] Update create facility to take in this address
- [x] Create the more unique uri
- [x] Do the same for the facility
- [x] Do the same for the facility
